baseURL = 'https://mdabrowski-eu.github.io/photography-basics/'
languageCode = 'pl'
title = 'Podstawy Fotografii'
theme = 'hugo-book'

[params]
  BookSection = 'docs'

[menu]
  [[menu.main]]
    identifier = 'wstep-budowa-aparatu'
    name = 'Jak zbudowany jest aparat'
    url = '/docs/wstep-budowa-aparatu/'
    weight = 10

  [[menu.main]]
    identifier = 'camera-obscura'
    name = 'Jak Działa Camera Obscura'
    url = '/docs/camera-obscura/'
    weight = 15

  [[menu.main]]
    identifier = 'soczewka'
    name = '2. Soczewka'
    url = '/docs/soczewka/'
    weight = 20

  [[menu.main]]
    identifier = 'migawka'
    name = '3. Migawka'
    url = '/docs/migawka/'
    weight = 30

  [[menu.main]]
    identifier = 'klisza'
    name = '4. Materiał światłoczuły'
    url = '/docs/klisza/'
    weight = 40

  [[menu.main]]
    identifier = 'matryca'
    name = '5 Matryca jako materiał światłoczuły'
    url = '/docs/matryca/'
    weight = 50

  [[menu.main]]
    identifier = 'przyslona'
    name = '6. Przysłona'
    url = '/docs/przyslona/'
    weight = 60

  [[menu.main]]
    identifier = 'fstops'
    name = '7. Dlaczego światło liczy się w przysłonach (f-stops)'
    url = '/docs/fstops/'
    weight = 70

  [[menu.main]]
    identifier = 'winietowanie'
    name = '8. Winietowanie'
    url = '/docs/winietowanie/'
    weight = 80

  [[menu.main]]
    identifier = 'dyfrakcja'
    name = '9. Dyfrakcja'
    url = '/docs/dyfrakcja/'
    weight = 90

  [[menu.main]]
    identifier = 'blysk'
    name = '10. Światło błyskowe'
    url = '/docs/blysk/'
    weight = 100

[markup]
  defaultMarkdownHandler = 'goldmark'
